package main

// CityTimezone represents a city with its timezone information
type CityTimezone struct {
	City       string   // City name
	Country    string   // Country name
	Timezone   string   // IANA timezone identifier
	Abbrevs    []string // Common abbreviations (e.g., EST, PST)
	Popularity int      // 1=major metro, 5=smaller city (for ranking)
}

// AllCities contains a comprehensive database of cities and their timezones
var AllCities = []CityTimezone{
	// ===== UNITED STATES - MAJOR CITIES =====
	{"New York", "United States", "America/New_York", []string{"EST", "EDT"}, 1},
	{"Los Angeles", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 1},
	{"Chicago", "United States", "America/Chicago", []string{"CST", "CDT"}, 1},
	{"Houston", "United States", "America/Chicago", []string{"CST", "CDT"}, 1},
	{"Phoenix", "United States", "America/Phoenix", []string{"MST"}, 1},
	{"Philadelphia", "United States", "America/New_York", []string{"EST", "EDT"}, 1},
	{"San Antonio", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"San Diego", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 1},
	{"Dallas", "United States", "America/Chicago", []string{"CST", "CDT"}, 1},
	{"San Jose", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 2},
	{"Austin", "United States", "America/Chicago", []string{"CST", "CDT"}, 1},
	{"Jacksonville", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"Fort Worth", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"Columbus", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"Charlotte", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"San Francisco", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 1},
	{"Indianapolis", "United States", "America/Indiana/Indianapolis", []string{"EST", "EDT"}, 2},
	{"Seattle", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 1},
	{"Denver", "United States", "America/Denver", []string{"MST", "MDT"}, 1},
	{"Boston", "United States", "America/New_York", []string{"EST", "EDT"}, 1},
	{"Nashville", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"Detroit", "United States", "America/Detroit", []string{"EST", "EDT"}, 2},
	{"Portland", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 2},
	{"Las Vegas", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 1},
	{"Memphis", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"Louisville", "United States", "America/Kentucky/Louisville", []string{"EST", "EDT"}, 3},
	{"Baltimore", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"Milwaukee", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"Albuquerque", "United States", "America/Denver", []string{"MST", "MDT"}, 3},
	{"Tucson", "United States", "America/Phoenix", []string{"MST"}, 3},
	{"Fresno", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 3},
	{"Mesa", "United States", "America/Phoenix", []string{"MST"}, 3},
	{"Sacramento", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 2},
	{"Atlanta", "United States", "America/New_York", []string{"EST", "EDT"}, 1},
	{"Kansas City", "United States", "America/Chicago", []string{"CST", "CDT"}, 2},
	{"Miami", "United States", "America/New_York", []string{"EST", "EDT"}, 1},
	{"Raleigh", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"Omaha", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Minneapolis", "United States", "America/Chicago", []string{"CST", "CDT"}, 1},
	{"Cleveland", "United States", "America/New_York", []string{"EST", "EDT"}, 2},
	{"Wichita", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Arlington", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},

	// ===== US STATE CAPITALS =====
	{"Montgomery", "United States", "America/Chicago", []string{"CST", "CDT"}, 4},
	{"Juneau", "United States", "America/Juneau", []string{"AKST", "AKDT"}, 4},
	{"Little Rock", "United States", "America/Chicago", []string{"CST", "CDT"}, 4},
	{"Sacramento", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 3},
	{"Hartford", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Dover", "United States", "America/New_York", []string{"EST", "EDT"}, 5},
	{"Tallahassee", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Honolulu", "United States", "Pacific/Honolulu", []string{"HST"}, 2},
	{"Boise", "United States", "America/Boise", []string{"MST", "MDT"}, 3},
	{"Springfield", "United States", "America/Chicago", []string{"CST", "CDT"}, 4},
	{"Des Moines", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Topeka", "United States", "America/Chicago", []string{"CST", "CDT"}, 5},
	{"Frankfort", "United States", "America/Kentucky/Louisville", []string{"EST", "EDT"}, 5},
	{"Baton Rouge", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Augusta", "United States", "America/New_York", []string{"EST", "EDT"}, 5},
	{"Annapolis", "United States", "America/New_York", []string{"EST", "EDT"}, 5},
	{"Lansing", "United States", "America/Detroit", []string{"EST", "EDT"}, 4},
	{"Saint Paul", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Jackson", "United States", "America/Chicago", []string{"CST", "CDT"}, 4},
	{"Jefferson City", "United States", "America/Chicago", []string{"CST", "CDT"}, 5},
	{"Helena", "United States", "America/Denver", []string{"MST", "MDT"}, 5},
	{"Lincoln", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Carson City", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 5},
	{"Concord", "United States", "America/New_York", []string{"EST", "EDT"}, 5},
	{"Trenton", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Santa Fe", "United States", "America/Denver", []string{"MST", "MDT"}, 4},
	{"Albany", "United States", "America/New_York", []string{"EST", "EDT"}, 3},
	{"Bismarck", "United States", "America/Chicago", []string{"CST", "CDT"}, 5},
	{"Oklahoma City", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Salem", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 4},
	{"Harrisburg", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Providence", "United States", "America/New_York", []string{"EST", "EDT"}, 3},
	{"Columbia", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Pierre", "United States", "America/Chicago", []string{"CST", "CDT"}, 5},
	{"Salt Lake City", "United States", "America/Denver", []string{"MST", "MDT"}, 2},
	{"Montpelier", "United States", "America/New_York", []string{"EST", "EDT"}, 5},
	{"Richmond", "United States", "America/New_York", []string{"EST", "EDT"}, 3},
	{"Olympia", "United States", "America/Los_Angeles", []string{"PST", "PDT"}, 4},
	{"Charleston", "United States", "America/New_York", []string{"EST", "EDT"}, 4},
	{"Madison", "United States", "America/Chicago", []string{"CST", "CDT"}, 3},
	{"Cheyenne", "United States", "America/Denver", []string{"MST", "MDT"}, 4},

	// ===== CANADA =====
	{"Toronto", "Canada", "America/Toronto", []string{"EST", "EDT"}, 1},
	{"Montreal", "Canada", "America/Montreal", []string{"EST", "EDT"}, 1},
	{"Vancouver", "Canada", "America/Vancouver", []string{"PST", "PDT"}, 1},
	{"Calgary", "Canada", "America/Edmonton", []string{"MST", "MDT"}, 2},
	{"Edmonton", "Canada", "America/Edmonton", []string{"MST", "MDT"}, 2},
	{"Ottawa", "Canada", "America/Toronto", []string{"EST", "EDT"}, 2},
	{"Winnipeg", "Canada", "America/Winnipeg", []string{"CST", "CDT"}, 2},
	{"Halifax", "Canada", "America/Halifax", []string{"AST", "ADT"}, 3},

	// ===== MEXICO & CENTRAL AMERICA =====
	{"Mexico City", "Mexico", "America/Mexico_City", []string{"CST", "CDT"}, 1},
	{"Guadalajara", "Mexico", "America/Mexico_City", []string{"CST", "CDT"}, 2},
	{"Monterrey", "Mexico", "America/Monterrey", []string{"CST", "CDT"}, 2},
	{"Tijuana", "Mexico", "America/Tijuana", []string{"PST", "PDT"}, 3},
	{"Cancun", "Mexico", "America/Cancun", []string{"EST"}, 3},
	{"Guatemala City", "Guatemala", "America/Guatemala", []string{"CST"}, 2},
	{"San Jose", "Costa Rica", "America/Costa_Rica", []string{"CST"}, 3},
	{"Panama City", "Panama", "America/Panama", []string{"EST"}, 3},

	// ===== SOUTH AMERICA =====
	{"Buenos Aires", "Argentina", "America/Argentina/Buenos_Aires", []string{"ART"}, 1},
	{"Sao Paulo", "Brazil", "America/Sao_Paulo", []string{"BRT"}, 1},
	{"Rio de Janeiro", "Brazil", "America/Sao_Paulo", []string{"BRT"}, 1},
	{"Brasilia", "Brazil", "America/Sao_Paulo", []string{"BRT"}, 2},
	{"Lima", "Peru", "America/Lima", []string{"PET"}, 1},
	{"Bogota", "Colombia", "America/Bogota", []string{"COT"}, 1},
	{"Santiago", "Chile", "America/Santiago", []string{"CLT"}, 1},
	{"Caracas", "Venezuela", "America/Caracas", []string{"VET"}, 2},

	// ===== EUROPE - WESTERN =====
	{"London", "United Kingdom", "Europe/London", []string{"GMT", "BST"}, 1},
	{"Dublin", "Ireland", "Europe/Dublin", []string{"IST", "GMT"}, 2},
	{"Edinburgh", "United Kingdom", "Europe/London", []string{"GMT", "BST"}, 3},
	{"Manchester", "United Kingdom", "Europe/London", []string{"GMT", "BST"}, 3},
	{"Paris", "France", "Europe/Paris", []string{"CET", "CEST"}, 1},
	{"Lyon", "France", "Europe/Paris", []string{"CET", "CEST"}, 3},
	{"Marseille", "France", "Europe/Paris", []string{"CET", "CEST"}, 3},
	{"Madrid", "Spain", "Europe/Madrid", []string{"CET", "CEST"}, 1},
	{"Barcelona", "Spain", "Europe/Madrid", []string{"CET", "CEST"}, 1},
	{"Lisbon", "Portugal", "Europe/Lisbon", []string{"WET", "WEST"}, 2},
	{"Amsterdam", "Netherlands", "Europe/Amsterdam", []string{"CET", "CEST"}, 1},
	{"Brussels", "Belgium", "Europe/Brussels", []string{"CET", "CEST"}, 2},
	{"Berlin", "Germany", "Europe/Berlin", []string{"CET", "CEST"}, 1},
	{"Munich", "Germany", "Europe/Berlin", []string{"CET", "CEST"}, 2},
	{"Hamburg", "Germany", "Europe/Berlin", []string{"CET", "CEST"}, 2},
	{"Frankfurt", "Germany", "Europe/Berlin", []string{"CET", "CEST"}, 2},
	{"Zurich", "Switzerland", "Europe/Zurich", []string{"CET", "CEST"}, 2},
	{"Geneva", "Switzerland", "Europe/Zurich", []string{"CET", "CEST"}, 3},
	{"Vienna", "Austria", "Europe/Vienna", []string{"CET", "CEST"}, 2},
	{"Rome", "Italy", "Europe/Rome", []string{"CET", "CEST"}, 1},
	{"Milan", "Italy", "Europe/Rome", []string{"CET", "CEST"}, 1},

	// ===== EUROPE - NORTHERN =====
	{"Stockholm", "Sweden", "Europe/Stockholm", []string{"CET", "CEST"}, 2},
	{"Oslo", "Norway", "Europe/Oslo", []string{"CET", "CEST"}, 2},
	{"Copenhagen", "Denmark", "Europe/Copenhagen", []string{"CET", "CEST"}, 2},
	{"Helsinki", "Finland", "Europe/Helsinki", []string{"EET", "EEST"}, 2},
	{"Reykjavik", "Iceland", "Atlantic/Reykjavik", []string{"GMT"}, 3},

	// ===== EUROPE - EASTERN =====
	{"Warsaw", "Poland", "Europe/Warsaw", []string{"CET", "CEST"}, 2},
	{"Prague", "Czech Republic", "Europe/Prague", []string{"CET", "CEST"}, 2},
	{"Budapest", "Hungary", "Europe/Budapest", []string{"CET", "CEST"}, 2},
	{"Bucharest", "Romania", "Europe/Bucharest", []string{"EET", "EEST"}, 2},
	{"Athens", "Greece", "Europe/Athens", []string{"EET", "EEST"}, 2},
	{"Istanbul", "Turkey", "Europe/Istanbul", []string{"TRT"}, 1},
	{"Moscow", "Russia", "Europe/Moscow", []string{"MSK"}, 1},
	{"Saint Petersburg", "Russia", "Europe/Moscow", []string{"MSK"}, 2},
	{"Kyiv", "Ukraine", "Europe/Kiev", []string{"EET", "EEST"}, 2},

	// ===== MIDDLE EAST =====
	{"Dubai", "United Arab Emirates", "Asia/Dubai", []string{"GST"}, 1},
	{"Abu Dhabi", "United Arab Emirates", "Asia/Dubai", []string{"GST"}, 2},
	{"Tel Aviv", "Israel", "Asia/Tel_Aviv", []string{"IST", "IDT"}, 1},
	{"Jerusalem", "Israel", "Asia/Jerusalem", []string{"IST", "IDT"}, 2},
	{"Riyadh", "Saudi Arabia", "Asia/Riyadh", []string{"AST"}, 1},
	{"Doha", "Qatar", "Asia/Qatar", []string{"AST"}, 2},
	{"Kuwait City", "Kuwait", "Asia/Kuwait", []string{"AST"}, 3},
	{"Beirut", "Lebanon", "Asia/Beirut", []string{"EET", "EEST"}, 3},
	{"Tehran", "Iran", "Asia/Tehran", []string{"IRST"}, 1},

	// ===== AFRICA =====
	{"Cairo", "Egypt", "Africa/Cairo", []string{"EET"}, 1},
	{"Lagos", "Nigeria", "Africa/Lagos", []string{"WAT"}, 1},
	{"Johannesburg", "South Africa", "Africa/Johannesburg", []string{"SAST"}, 1},
	{"Cape Town", "South Africa", "Africa/Johannesburg", []string{"SAST"}, 2},
	{"Nairobi", "Kenya", "Africa/Nairobi", []string{"EAT"}, 2},
	{"Accra", "Ghana", "Africa/Accra", []string{"GMT"}, 3},
	{"Casablanca", "Morocco", "Africa/Casablanca", []string{"WET"}, 2},
	{"Algiers", "Algeria", "Africa/Algiers", []string{"CET"}, 3},
	{"Tunis", "Tunisia", "Africa/Tunis", []string{"CET"}, 3},

	// ===== ASIA - EAST =====
	{"Tokyo", "Japan", "Asia/Tokyo", []string{"JST"}, 1},
	{"Osaka", "Japan", "Asia/Tokyo", []string{"JST"}, 1},
	{"Seoul", "South Korea", "Asia/Seoul", []string{"KST"}, 1},
	{"Beijing", "China", "Asia/Shanghai", []string{"CST"}, 1},
	{"Shanghai", "China", "Asia/Shanghai", []string{"CST"}, 1},
	{"Hong Kong", "Hong Kong", "Asia/Hong_Kong", []string{"HKT"}, 1},
	{"Taipei", "Taiwan", "Asia/Taipei", []string{"CST"}, 1},
	{"Manila", "Philippines", "Asia/Manila", []string{"PHT"}, 1},

	// ===== ASIA - SOUTHEAST =====
	{"Singapore", "Singapore", "Asia/Singapore", []string{"SGT"}, 1},
	{"Bangkok", "Thailand", "Asia/Bangkok", []string{"ICT"}, 1},
	{"Kuala Lumpur", "Malaysia", "Asia/Kuala_Lumpur", []string{"MYT"}, 1},
	{"Jakarta", "Indonesia", "Asia/Jakarta", []string{"WIB"}, 1},
	{"Ho Chi Minh City", "Vietnam", "Asia/Ho_Chi_Minh", []string{"ICT"}, 2},
	{"Hanoi", "Vietnam", "Asia/Ho_Chi_Minh", []string{"ICT"}, 2},

	// ===== ASIA - SOUTH =====
	{"Mumbai", "India", "Asia/Kolkata", []string{"IST"}, 1},
	{"Delhi", "India", "Asia/Kolkata", []string{"IST"}, 1},
	{"Bangalore", "India", "Asia/Kolkata", []string{"IST"}, 1},
	{"Kolkata", "India", "Asia/Kolkata", []string{"IST"}, 2},
	{"Chennai", "India", "Asia/Kolkata", []string{"IST"}, 2},
	{"Hyderabad", "India", "Asia/Kolkata", []string{"IST"}, 2},
	{"Karachi", "Pakistan", "Asia/Karachi", []string{"PKT"}, 1},
	{"Lahore", "Pakistan", "Asia/Karachi", []string{"PKT"}, 2},
	{"Dhaka", "Bangladesh", "Asia/Dhaka", []string{"BST"}, 1},
	{"Colombo", "Sri Lanka", "Asia/Colombo", []string{"IST"}, 3},

	// ===== OCEANIA =====
	{"Sydney", "Australia", "Australia/Sydney", []string{"AEDT", "AEST"}, 1},
	{"Melbourne", "Australia", "Australia/Melbourne", []string{"AEDT", "AEST"}, 1},
	{"Brisbane", "Australia", "Australia/Brisbane", []string{"AEST"}, 2},
	{"Perth", "Australia", "Australia/Perth", []string{"AWST"}, 2},
	{"Adelaide", "Australia", "Australia/Adelaide", []string{"ACDT", "ACST"}, 2},
	{"Auckland", "New Zealand", "Pacific/Auckland", []string{"NZDT", "NZST"}, 1},
	{"Wellington", "New Zealand", "Pacific/Auckland", []string{"NZDT", "NZST"}, 2},
	{"Fiji", "Fiji", "Pacific/Fiji", []string{"FJT"}, 3},

	// ===== CARIBBEAN =====
	{"Havana", "Cuba", "America/Havana", []string{"CST", "CDT"}, 3},
	{"Kingston", "Jamaica", "America/Jamaica", []string{"EST"}, 3},
	{"San Juan", "Puerto Rico", "America/Puerto_Rico", []string{"AST"}, 3},
	{"Port-au-Prince", "Haiti", "America/Port-au-Prince", []string{"EST"}, 4},
}
